version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    # command: --default-time-zone=+08:00
    environment:
      MYSQL_DATABASE: $DATABASE
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 3306:3306

  api:
    build: ./rrs-api
    restart: always
    environment:
      DB_HOST: db
      DATABASE: $DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    ports:
      - 5000:5000
    depends_on:
      - db
  ui:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # use `http://api:5000` in nginx.conf as `proxy_pass`
      - ./rrs-ui/build:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - api
